server:
  port: 80
  compression:
    enabled: true
    mime-types: application/json

spring:
  datasource: #rw
      url: jdbc:mysql://47.98.145.250/wx_db?useUnicode=true&characterEncoding=utf-8
      username: root
      password: 123456
      dbcp2:
        initial-size: 10
        max-total: 20
        connection-init-sqls: "set names 'utf8mb4'"
  cache:
      type: redis
      redis:
        time-to-live: 10M
  redis:
      host: 127.0.0.1
      password:
      jedis:
        pool:
          max-active: 20
          max-idle: 10
      database: 0
  freemarker:
    template-loader-path: classpath:/templates/
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftl
  resources:
    static-locations: classpath:/static,classpath:/public,classpath:/resources,classpath:/META-INF/resources
  jpa:
      show-sql: true
      open-in-view: false
  logging:
    level:
      root: WARN
    pattern:
      console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

